# Generated by Django 5.2 on 2025-05-19 18:55

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('language', models.CharField(blank=True, help_text='Primary language', max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, help_text='Nationality adjective', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], help_text="Number of years—for example, '1', '1.5', '2', etc.", max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('default', 'Default'), ('company', 'Company'), ('agent', 'Agent')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_users', to='core.city'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('tax_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='core.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_users', to='core.country'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('near_to_close', 'Near to Close'), ('quota_full', 'Quota Full'), ('closed', 'Closed')], default='available', max_length=15)),
                ('degree', models.CharField(choices=[('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('integrated_phd', 'Integrated PhD')], max_length=20)),
                ('duration', models.CharField(blank=True, choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='Duration in years; should be one of the faculty’s year options', max_length=10)),
                ('deposit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prep_school_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('semester_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee per semester', max_digits=12, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offer', models.DecimalField(blank=True, decimal_places=2, help_text='Scholarship or discount offered', max_digits=10, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.faculty')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.termoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_type', models.CharField(choices=[('transfer', 'Transfer Student'), ('first_year', 'First-Year Student')], default='first_year', max_length=15)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('failed', 'Failed')], default='in_progress', max_length=15)),
                ('step', models.IntegerField(choices=[(1, 'Step One'), (2, 'Step Two'), (3, 'Step Three'), (4, 'Step Four'), (5, 'Step Five'), (6, 'Step Six'), (7, 'Step Seven')], default=1)),
                ('application_name', models.CharField(editable=False, help_text='Auto-generated application code', max_length=12, unique=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to=core.models.application_document_upload_to)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'default'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=50)),
                ('language', models.ForeignKey(blank=True, help_text='Select the country whose language you speak', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, null=True)),
                ('academic_calendar', models.TextField(blank=True, help_text='Academic calendar details')),
                ('sector', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('other', 'Other')], default='private', max_length=20)),
                ('founded_in', models.PositiveIntegerField(blank=True, help_text='Year founded, e.g. 2013', null=True)),
                ('main_campus', models.CharField(blank=True, max_length=255)),
                ('pin_code', models.CharField(blank=True, help_text='University PIN code', max_length=20, null=True)),
                ('available_languages', models.ManyToManyField(blank=True, help_text='Which country languages are taught/used by this university', related_name='language_universities', to='core.country')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='core.country')),
                ('faculties', models.ManyToManyField(blank=True, related_name='universities', to='core.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='year_options',
            field=models.ManyToManyField(blank=True, help_text='Select one or more possible durations (in years) that this faculty offers.', related_name='faculties', to='core.yearoption'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
