# Generated by Django 5.2 on 2025-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_name_country_country_name_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='ID from info.studyfans.com', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='ID from info.studyfans.com', null=True, unique=True),
        ),
    ]
