# Generated by Django 5.2 on 2025-05-22 09:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_program_external_id_university_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='academic_calendar',
        ),
        migrations.AddField(
            model_name='university',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed details (dates, exams, documents, fees, etc.) from the site'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='university_name_ci_unique'),
        ),
    ]
