# Generated by Django 5.2 on 2025-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_university_academic_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='ID from info.studyfans.com', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='ID from info.studyfans.com', null=True, unique=True),
        ),
    ]
