# Generated by Django 5.2 on 2025-06-02 00:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_city_external_id_country_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_representative',
            field=models.BooleanField(default=False, help_text='Designates whether this student can access representative features'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (max 2MB)', null=True, upload_to=core.models.user_profile_image_path, validators=[core.models.validate_image_file_extension], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=core.models.application_document_upload_to, validators=[core.models.validate_document_file_extension], verbose_name='Application Documents'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], help_text="Duration in years; should be one of the faculty's year options", max_length=10),
        ),
    ]
