# Generated by Django 5.2 on 2026-08-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_representative_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('associate_bachelor', 'Associate & Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (1, 2, 3...)')),
                ('icon_class', models.CharField(default='fas fa-star', help_text='FontAwesome class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Journey Step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='+905344615317', max_length=20)),
                ('email', models.EmailField(default='Matinf1060@gmail.com', max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('hero_title', models.CharField(default='Unlock Your Fully Funded Future.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('hero_background_image', models.ImageField(default='home/hero.jpg', upload_to='home/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/'),
        ),
        migrations.AddField(
            model_name='university',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Display in the trust banner?'),
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=50)),
                ('degree_level', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('instagram_video_url', models.URLField(blank=True, help_text='Link to the Instagram video', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('destination_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
            options={
                'verbose_name': 'Success Story',
            },
        ),
    ]
