# Generated by Django 5.2 on 2026-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_documentrequirement_howitworksstep_sitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_fa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ar',
            field=models.CharField(default='Unlock Your Fully Funded Future.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='Unlock Your Fully Funded Future.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_fa',
            field=models.CharField(default='Unlock Your Fully Funded Future.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_tr',
            field=models.CharField(default='Unlock Your Fully Funded Future.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='degree_level_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='degree_level_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='degree_level_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='degree_level_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='origin_country_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='origin_country_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='origin_country_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='origin_country_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='quote_tr',
            field=models.TextField(null=True),
        ),
    ]
