# Generated by Django 5.2 on 2026-08-22 08:56

import core.utils.image_processing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentrequirement_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_processing.university_logo_upload_to),
        ),
    ]
