# Generated by Django 5.2.5 on 2026-09-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from public site while preserving applications.'),
        ),
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from public site while preserving applications.'),
        ),
    ]
