# Generated by Django 5.2.5 on 2026-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_program_is_active_university_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency code, e.g. USD, EUR, TRY', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(blank=True, help_text='Language of instruction, e.g. English, Turkish', max_length=50),
        ),
    ]
