# Generated by Django 5.2.5 on 2026-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userinfo_remove_university_available_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background_image',
            field=models.ImageField(default='static/images/home/hero.jpg', upload_to='home/'),
        ),
    ]
