# Generated by Django 5.2.5 on 2026-09-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sitesettings_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, help_text='Student photo for the homepage story card. Falls back to an initial avatar when empty.', null=True, upload_to='success_stories/'),
        ),
    ]
