# Generated by Django 5.2.5 on 2026-09-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_successstory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
