# Generated by Django 5.2.5 on 2026-09-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_city_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'Agent Profile', 'verbose_name_plural': 'Agent Profiles'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='termoption',
            options={'verbose_name': 'Term Option', 'verbose_name_plural': 'Term Options'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='yearoption',
            options={'verbose_name': 'Year Option', 'verbose_name_plural': 'Year Options'},
        ),
    ]
