# Generated by Django 5.2.5 on 2026-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_agentprofile_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='The current email address has been confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email address awaiting verification; empty when no change is in progress', max_length=254, null=True),
        ),
    ]
