# Generated by Django on 2026-09-26

from django.db import migrations


def forwards(apps, schema_editor):
    """Mark accounts that already passed registration as email-verified.

    Every active user confirmed their address through the registration code
    (or was created by an agent), so retroactively requiring a new verification
    would lock the entire existing base out of the dashboard on deploy.
    """
    User = apps.get_model("core", "User")
    User.objects.filter(is_active=True).update(email_verified=True)


def backwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.update(email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_user_email_verified_user_pending_email"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
