# Generated by Django 5.2 on 2025-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
