# Generated by Django 5.2 on 2025-06-01 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_verificationcode_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['token'], name='authenticat_token_dc593a_idx'),
        ),
    ]
