# Generated by Django 5.2.5 on 2026-09-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_verificationcode_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Code', 'verbose_name_plural': 'Verification Codes'},
        ),
    ]
