# Generated by Django 5.2.5 on 2026-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_verificationcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=12),
        ),
    ]
