# Generated by Django 5.2 on 2025-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(help_text='Current connect.sid cookie value', max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stored ConnectSID',
                'verbose_name_plural': 'Stored ConnectSIDs',
            },
        ),
    ]
